<a href="https://colab.research.google.com/github/jajllc/DevTown/blob/main/DevTown_Excel_Python_Day3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Importing Libraries
import numpy as np
import pandas as pd

In [4]:
df=pd.read_excel("/content/sales2.xlsx")

/usr/local/lib/python3.12/dist-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Slicer List extension is not supported and will be removed
  warn(msg)

In [6]:
df.head()

,Order ID,Date,Product,Category,Region,Quantity,Price,Sales
0,1001,2026-01-01 00:00:00,Laptop,Electronics,North,2.0,50000.0,100000.0
1,1002,2026-01-02 00:00:00,Mouse,Electronics,South,5.0,500.0,2500.0
2,1003,2026-01-03 00:00:00,Chair,Furniture,East,3.0,4000.0,12000.0
3,1004,2026-01-04 00:00:00,Laptop,Electronics,West,1.0,50000.0,6000.0
4,1005,2026-01-05 00:00:00,Desk,Furniture,North,2.0,10000.0,20000.0

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13 entries, 0 to 12
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Order ID  12 non-null     object
 1   Date      12 non-null     object
 2   Product   8 non-null      object
 3   Category  8 non-null      object
 4   Region    8 non-null      object
 5   Quantity  8 non-null      float64
 6   Price     8 non-null      float64
 7   Sales     9 non-null      float64
dtypes: float64(3), object(5)
memory usage: 964.0+ bytes

In [7]:
df.tail()

,Order ID,Date,Product,Category,Region,Quantity,Price,Sales
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,211500.0
9,Row Labels,Sum of Sales,NaN,NaN,NaN,NaN,NaN,NaN
10,East,5000,NaN,NaN,NaN,NaN,NaN,NaN
11,South,2500,NaN,NaN,NaN,NaN,NaN,NaN
12,Grand Total,7500,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df.describe()

        Quantity         Price          Sales
count   8.000000      8.000000       9.000000
mean    3.500000  21125.000000   47000.000000
std     2.976095  24090.232164   69118.105443
min     1.000000    500.000000    2500.000000
25%     1.750000   3125.000000    6000.000000
50%     2.500000   7000.000000   16000.000000
75%     4.250000  50000.000000   50000.000000
max    10.000000  50000.000000  211500.000000

In [9]:
df.shape

(13, 8)

In [10]:
df.columns

Index(['Order ID', 'Date', 'Product', 'Category', 'Region', 'Quantity',
       'Price', 'Sales'],
      dtype='object')

# Filtering

In [11]:
df[df['Region']=="North"]

,Order ID,Date,Product,Category,Region,Quantity,Price,Sales
0,1001,2026-01-01 00:00:00,Laptop,Electronics,North,2.0,50000.0,100000.0
4,1005,2026-01-05 00:00:00,Desk,Furniture,North,2.0,10000.0,20000.0
7,1008,2026-01-08 00:00:00,Laptop,Electronics,North,1.0,50000.0,50000.0

In [14]:
# Filter electronic catagory
df[df['Category']=="Electronics"]

,Order ID,Date,Product,Category,Region,Quantity,Price,Sales
0,1001,2026-01-01 00:00:00,Laptop,Electronics,North,2.0,50000.0,100000.0
1,1002,2026-01-02 00:00:00,Mouse,Electronics,South,5.0,500.0,2500.0
3,1004,2026-01-04 00:00:00,Laptop,Electronics,West,1.0,50000.0,6000.0
5,1006,2026-01-06 00:00:00,Mouse,Electronics,East,10.0,500.0,5000.0
7,1008,2026-01-08 00:00:00,Laptop,Electronics,North,1.0,50000.0,50000.0

In [16]:
df.sort_values("Sales", ascending=False)

,Order ID,Date,Product,Category,Region,Quantity,Price,Sales
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,211500.0
0,1001,2026-01-01 00:00:00,Laptop,Electronics,North,2.0,50000.0,100000.0
7,1008,2026-01-08 00:00:00,Laptop,Electronics,North,1.0,50000.0,50000.0
4,1005,2026-01-05 00:00:00,Desk,Furniture,North,2.0,10000.0,20000.0
6,1007,2026-01-07 00:00:00,Chair,Furniture,South,4.0,4000.0,16000.0
2,1003,2026-01-03 00:00:00,Chair,Furniture,East,3.0,4000.0,12000.0
3,1004,2026-01-04 00:00:00,Laptop,Electronics,West,1.0,50000.0,6000.0
5,1006,2026-01-06 00:00:00,Mouse,Electronics,East,10.0,500.0,5000.0
1,1002,2026-01-02 00:00:00,Mouse,Electronics,South,5.0,500.0,2500.0
9,Row Labels,Sum of Sales,NaN,NaN,NaN,NaN,NaN,NaN
10,East,5000,NaN,NaN,NaN,NaN,NaN,NaN
11,South,2500,NaN,NaN,NaN,NaN,NaN,NaN
12,Grand Total,7500,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
# Sort for High Qty at top

In [20]:
df.sort_values("Quantity", ascending=False)

,Order ID,Date,Product,Category,Region,Quantity,Price,Sales
5,1006,2026-01-06 00:00:00,Mouse,Electronics,East,10.0,500.0,5000.0
1,1002,2026-01-02 00:00:00,Mouse,Electronics,South,5.0,500.0,2500.0
6,1007,2026-01-07 00:00:00,Chair,Furniture,South,4.0,4000.0,16000.0
2,1003,2026-01-03 00:00:00,Chair,Furniture,East,3.0,4000.0,12000.0
4,1005,2026-01-05 00:00:00,Desk,Furniture,North,2.0,10000.0,20000.0
0,1001,2026-01-01 00:00:00,Laptop,Electronics,North,2.0,50000.0,100000.0
3,1004,2026-01-04 00:00:00,Laptop,Electronics,West,1.0,50000.0,6000.0
7,1008,2026-01-08 00:00:00,Laptop,Electronics,North,1.0,50000.0,50000.0
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,211500.0
9,Row Labels,Sum of Sales,NaN,NaN,NaN,NaN,NaN,NaN
10,East,5000,NaN,NaN,NaN,NaN,NaN,NaN
11,South,2500,NaN,NaN,NaN,NaN,NaN,NaN
12,Grand Total,7500,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
#KPI Values
# Total Revenue
df['Sales'].sum()

np.float64(423000.0)

In [24]:
#Average Sale
df['Sales'].mean()

np.float64(47000.0)

In [25]:
# Highest Sale
df['Sales'].max()

211500.0

In [26]:
#Lowest Sale
df['Sales'].min()

2500.0

In [27]:
#Total Orders
df['Order ID'].count()

np.int64(12)